from dataclasses_json import dataclass_json, LetterCase

from youtube_data_reader.models._identified_model_base import _IdentifiedModelBase
from youtube_data_reader.models.subscriptions.subscription_content_details import SubscriptionContentDetails
from youtube_data_reader.models.subscriptions.subscription_snippet import SubscriptionSnippet
from youtube_data_reader.models.subscriptions.subscription_subscriber_snippet import SubscriptionSubscriberSnippet
from youtube_data_reader.models.utils import defaulted_dataclass


@dataclass_json(letter_case=LetterCase.CAMEL)
@defaulted_dataclass
class Subscription(_IdentifiedModelBase):
    content_details: SubscriptionContentDetails
    snippet: SubscriptionSnippet
    subscriber_snippet: SubscriptionSubscriberSnippet
