name: Pylint

on:
  push:
    paths:
      - 'youtube_data_reader/**'
      - '.github/workflows/pylint.yml'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint

      - name: Analysing the code with pylint
        run: |
          pylint youtube_data_reader --exit-zero | tee pylint.txt
          echo "pylint_artifact_name=Pylint_$(sed -n 's/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p' pylint.txt)" >> $GITHUB_ENV

      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: ${{ env.pylint_artifact_name }}
          path: pylint.txt
