name: Pylint

on:
  push:
    paths-ignore:
      - 'docs/**'

jobs:
  lint:

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v1
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pylint
      - name: Analysing the code with pylint
        run: pylint src/youtube_data_reader --exit-zero > .github/workflows/pylint.out
      - name: Extracting pylint results
        run: grep "." .github/workflows/pylint.out | tail -1 > .github/workflows/pylint.score
      - name: Upload artifacts
        uses: actions/upload-artifact@v2
        with:
          name: pylint-score
          path: .github/workflows/pylint.score
